### ISSUE TITLE
ReduxでTodoリスト作成 - 削除ボタン

### ISSUE THREAD

**Issue by sw-otay** [sw-kanekoi/kanekoi-training-react-2#1]
削除ボタンを押すと選択していないToDoリストまで消えてしまいます。

**Comment by sw-otay** [comment]
ToDoリストを複数追加して1個だけ削除したい時です。

**Comment by sw-kanekoi** [comment]
修正いたしました。
原因：削除対象のタスクをタスク名で検索しているため、同じタスク名のタスクが複数ある場合にまとめて削除されてしまう。
修正：[]タスクのデータ構成に[id]と、別でidの最大値[maxId]を追加。タスク追加時にmaxIdを更新。タスク削除時にidで対象タスクを検索し削除。

**Comment by sw-otay** [comment]
修正されたことを確認しました！
