### ISSUE TITLE
Redux1:「Reac初心者でも読めば必ずわかるReactのRedux講座」

### ISSUE THREAD

**Issue by sw-otay** [sw-kanekoi/kanekoi-training-react-2#2]
UP,DOWNボタンを押すとエラーが発生しますので確認をお願いします。

**Comment by sw-kanekoi** [comment]
修正いたしました。
原因：UP, DOWNのactionでは、stateの中のcountしか更新せず、同じくstateのpostsが更新時にセットされていなかった。
修正：UP,DOWNのaction内のstateセット時に、[...state]を追加し、postsを含むstate全体が更新されるようにした。

**Comment by sw-otay** [comment]
修正されたことを確認しました！
